### ISSUE TITLE
Add a table of contents / index

### ISSUE THREAD

**Issue by hollsk** [springernature/frontend-playbook#159]
We've got a fair chunk of information but no real organisation, so it's a bit overwhelming when you open up the repo. 

The [house style](https://github.com/springernature/frontend-playbook/blob/master/practices/house-style.md) page has transmogrified into a getting-started guide of sorts, but it doesn't include references to every file. 

Propose we add an index that groups files into logical order, to give readers some idea of priority and structure. Maybe something like this:

- House Style
  - Accessibility
  - Accessibility checklist
    - Effective colour contrast
  - Code review
  - Graded browser support
- Markup 
- CSS
  - OOCSS
  - BEM 
  - Mosiac CSS
- JavaScript
- Node
  - Dependency managment
  - Semver
  - Tools

And so on (not a comprehensive list). Does this look like an ok idea?

**Comment by joseluisbolos** [comment]
Yep, I was planning to do this myself... (eventually) to complement the TOC that were created on every page on #144.

One thing that I would suggest is to add a brief description under every link, so people know where to click.

It may be worth looking at a tool to do this for ourselves because, as we keep adding stuff to the Playbook, the TOC may become difficult to maintain. There are plugins for creating in-page TOCs, which I used for #144. There probably must be something that deals with several files.

**Comment by hollsk** [comment]
On reflection, I don't think this is necessary anymore. Now that we've created individual categories, the directory listing itself does the same job, with no effort. 

Let us close this issue, with a feeling of triumphant achievement ✨ 😤 ✨
