### ISSUE TITLE
JavaScript Code commenting

### ISSUE THREAD

**Issue by nickcall** [springernature/frontend-playbook#28]
We need to create a document that details what level and style of commenting we require in our code. This relates to #27

**Comment by dotcode** [comment]
This ticket relates specifically to JavaScript comments. 

Let's detail code style - to do that let's first add some examples in this ticket - what conventions do we currently use?

We might want to later on talk more generally about commenting in terms of detailing the "why" rather than the "how" (for instance if using code which would raise eyebrows, explain your reasoning - why have you done it using method "foo", when method "bar" would normally be used?)

**Comment by joseluisbolos** [comment]
Just checking. Is this still needed?

**Comment by jpw** [comment]
Seems to be, there is nothing pertaining to comments in https://github.com/springernature/frontend-playbook/blob/master/technologies/javascript.md

**Comment by andrewmee** [comment]
I'd suggest we might just need to expand this "Code should be self-documenting where possible" bit in https://github.com/springernature/frontend-playbook/blob/master/technologies/javascript.md#code-for-humans

**Comment by umaar** [comment]
Done! https://github.com/springernature/frontend-playbook/commit/72b1209bc28367d96c0f120feb1b7e7434786203
