### ISSUE TITLE
Tidy up (and add) "arrow functions" sections

### ISSUE THREAD

**Issue by dotcode** [springernature/frontend-playbook#56]
We have this text for the "arrow functions" section. It's OK, but needs to use our "we do/we don't do" style. Therefore need to add a couple of extra examples (of what we don't do).
#### Arrow Functions

If the environment you're running in supports ES2015 (Node.js 4.x/[Babel](https://babeljs.io/)) then you can use arrow functions in place of anonymous JavaScript functions:

``` js
['FOO', 'BAR', 'BAZ'].map(string => string.toLowerCase());
```

Arrow function arguments do not need to be wrapped in brackets if there is only one.

Arrow functions can be on a single line if they don't require curly braces. For arrow functions with multiple statements, they _must_ be multi-line:

``` js
doSomethingAsync((error, result) => {
    if (error) {
        return console.error(error);
    }
    console.log(result);
});
```

Arrow functions should not be used everywhere, only where otherwise an anonymous function would be used. You shouldn't replace your named functions with arrow functions:

``` js
var myFunction = (foo) => {
    console.log('Do not do this');
}
```

**Comment by joseluisbolos** [comment]
Could someone familiar with ES2015 features please create a PR for this? 👍

**Comment by hollsk** [comment]
I'm in the process of fleshing this out now after we had a chat about it in Slack this morning. One thing that strikes me is that the "we do/we don't do" format is pretty difficult to write for this because there are really not that many hard and fast rules. We shouldn't use arrow functions for named functions, and we certainly shouldn't use them to create unreadable bollocks like this: `let multiply = (a, b) => b === undefined ? b => a * b : a * b;`. 

Beyond that, all the other use cases are wholly dependent on the what the code is doing - it's not just a syntactical thing that we can reasonably confine to house style. If we try to make this prescriptive then we limit our own freedom to choose the best abstraction for the purpose 😱  The only thing that's similar to this in the Playbook is the async section, which doesn't follow the we do/don't format for the same reason. 

So, I _really really really_ don't want to write 1500 words on lexical scope and prototypal context, with code examples. Not because it isn't interesting (it is!), but because it's a huge topic, and the playbook should be a short guide. On top of that arrow functions aren't a like-for-like replacement for anonymous function expressions, so it doesn't make sense to recommend one over the other.

I'm going to add one we do/don't (use arrow funcs for callbacks), because the linter will make the same recommendation. The rest is still going to be pretty fuzzy. 

An alternative would be to just _not have this section at all_, and leave it up to the developers to decide, and for the linter to flag up any specific areas that it thinks could be improved.

**Comment by jweidler** [comment]
I would suggest to use arrow functions only in a functional programming context. It could be a way for a developer to indicate that a function (yes, it may be a named function then) is pure, for example. This makes more sense because like @hollsk said it's not just a syntactical thing and this way you can keep the "We do/we don't" part brief in the code style guide and refer to external sources to clarify specifics. 

To be honest, I have been writing arrow functions all over the place because I just like their brevity and aesthetics but I actually might start enforcing the above rule on myself from now on :-)

**Comment by danyalaytekin** [comment]
Agreed.  Functional programming, some callbacks, and the odd very short function (especially when defined to be used a couple of lines afterwards).  With none of this enforced by a linter.

**Comment by jweidler** [comment]
Right, things like `prefer-arrow-callback` shouldn't be linted. I would only define low-level syntax and formatting style rules such as `arrow-parens`, `arrow-body-style` and `arrow-spacing`.

**Comment by jpw** [comment]
I want their goodness whether functional or not. Functional programming approaches are not always suitable.

**Comment by hollsk** [comment]
The more I think about it, the less I want to put this in the playbook at all. I don't think there's a lot of value in repeating lint rules here (like AirBnB do) because... well, we've got linters already, and we agree per-team on any additional lint settings that we want to use. 

The decision as to when to use one is really subjective. We don't have an equivalent section in the Playbook for when to use a function expression or a named function, we don't have anything on when to use lexical scoping vs dynamic binding - it wouldn't really make sense to lay down rules on that. I'm struggling at this stage to see why arrow functions should be any different.

If they make sense for your code, they meet the relevant lint rules that your team has agreed on, and everyone you're working with understands what you've written, surely it's just a basic programming decision?

**Comment by jpw** [comment]
- there are some examples in the "don'ts" the linting makes kinda redundant, but they are useful for new hires to quickly scan over and get into the style, so I don't have a prob with that myself.
- some bits, like the arrow functions and async/await are great content, but verge into tutorial territory, rather than code style. The title of the doc is "JavaScript Style Guide" after all. Maybe move them into `frontend-playbook/practices/` ? Not sure...

**Comment by jweidler** [comment]
If this is merely about low-level code style leave it to the linters and remove it/don't add anything.

**Comment by hollsk** [comment]
I like this guy ^ 

😄

**Comment by jweidler** [comment]
Haha, yes, I'm sorry, maybe I should have read the playbook first and then read this issue in the proper context … This issue is more about how to separate code style guide rules into simple visual rules (readability, consistent look) and more logic-focussed best practices I guess. The same would apply to https://github.com/springernature/frontend-playbook/blob/master/technologies/javascript.md#pure-functions in my opinion.

**Comment by hollsk** [comment]
No, I agree :D I feel a bit like the arrow functions section was in the old Nature playbook (where the original content in the OP came from) because it was new and shiny, not because it reflected any actual house style. 

Might be worth making sure that we all have the same idea of what the Playbook is supposed to be - a guide to how _we_ are expected to write software, here at this company, not a guide to how to write software generally. 

A few people have suggested that this (and other tutorial-style content) would probably be a better fit for a [cruft.io](http://cruft.io) post, and I agree (although I don't care enough about the topic to write that myself 😝 )

So, I'm going to just close this issue without doing anything. Sorry Jude! If you (or somebody else) disagrees then you can reopen it, but right now I'm all like ¯\_(ツ)_/¯
